version: '3.8'

services:
  # --- Servicio Backend ---
  backend:
    build: ./backend
    container_name: mi-app-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CLIENT_URL=http://localhost:80
    # Carga variables del archivo .env local
    env_file:
      - ./backend/.env
    networks:
      - app-network

  # --- Servicio Frontend ---
  frontend:
    build: ./frontend
    container_name: mi-app-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

# Red compartida
networks:
  app-network:
    driver: bridge